export const SHARE_LINK='https://turbokirichenko.github.io/ton-coeur-app/'
export const SHARE_TEXT='A simple touch can create something magical. Just to click and gift ❤️'
export const SHARE_TITLE='TonCœur Mini Telegram App'
export const TG_SHARE_API='https://t.me/share/url?url='
export const TG_APP_LINK='https://t.me/ton_coeur_dev_bot/toncouer'